version: "3.3"
services:
  web:
    build: .
    ports:
      - "4000:4000"
    volumes:
      - ./img/:/src/jekyll/img/:ro
      - ./_config.yml:/src/jekyll/config.yml:ro
      - ./_includes/about_me.html:/src/jekyll/_includes/about_me.html:ro
      - ./_includes/interests.html:/src/jekyll/_includes/interests.html:ro
    labels: 
      - traefik.enable=true
      - traefik.http.routers.unsecureOnepage.entrypoints=http
      - traefik.http.routers.unsecureOnepage.rule=Host(`${SUBDOMAIN}${DOMAIN}`)
      - traefik.http.routers.unsecureOnepage.middlewares=redirect@file

      - traefik.http.routers.onepage.entrypoints=https
      - traefik.http.routers.onepage.rule=Host(`${SUBDOMAIN}${DOMAIN}`)
      - traefik.http.routers.onepage.tls.certresolver=${TRAEFIKCERT}
      - traefik.http.routers.onepage..loadbalancer.server.port=4000

